### ISSUE TITLE
Prepare grapes dataset

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#11]
Take the first steps towards creating a train/val dataset for our CNN treatment of grapes on the vine.

Feel free to edit this first comment to specify your goals for this milestone, @ivanprado.

**Comment by ivanprado** [comment]
@amlarraz has trained a Faster-RCNN model with a grapes dataset and results are pretty promising. I propose the following next steps:

- [X] Isolate a dataset just with clusters. That will need a tool for cropping images from bboxes
- [x] Label clusters to have a dataset. 
- [x] Train deeplab with the dataset.
- [ ] Try to detect individual grapes, and get information as cluster compactness, etc. 

I think I can take care of 1 and 4 and @amlarraz can work on 2 and 3. 

@amlarraz how do you see this plan? I will need you to upload the dataset to S3 so that I can work on point 1.

**Comment by amlarraz** [comment]
I see all perfect @ivanprado, however first I'm going to finish the labelling in the entire dataset (only have 140 images labelled from 300), and then I'll upload to S3, launch another training with all images, and go to segmentation tasks 2 and 3. Do you think is ok or do you want I upload the things I already have to test?

**Comment by ivanprado** [comment]
@amlarraz perfect, go ahead! I can work on 1 without the dataset.

**Comment by ivanprado** [comment]
I have created [a tool](https://github.com/splashblot/lettuces/blob/master/vegy/tools/voc_cropper.py) for cropping isolated objects from annotations.

Crops uploaded to S3. @amlarraz look at folder Crops.

**Comment by amlarraz** [comment]
Maybe we can use the approach in: http://www.vitivinicultura.net/tecnologia-vinedo.html to detect the cluster compactness

**Comment by ivanprado** [comment]
Sure, that can be a starting point.

**Comment by amlarraz** [comment]
Created a tool to run through the "complete inference", meaning:

1.- Create inferences in Faster-RCNN (works in faster-rcnn-Tensorflow)
2.- Crop the bboxes detected in Faster-RCNN and make inferences using DeeplabV2 (Tensorflow) over this crops.
3.- Draw the DeeplabV2 inference smoothy-border over each crop.
4.- Overlap the crops and the original image and draw the faster-RCNN bboxes and save.
