### ISSUE TITLE
Change default max_layers beyond the current 8

### ISSUE THREAD

**Issue by apercas** [splashblot/dronedb#57]
After a quick talk with Diego he complained about being impossible for him to add more layers once you get to the eight. Maybe a CARTO limitation I don't know.

**Comment by jjmata** [comment]
Why #bug?

**Comment by jjmata** [comment]
This is not a bug, but a pricing level decision made on the Carto codebase:

https://github.com/CartoDB/cartodb/blob/fca87ab3b7c44529553cd1b059b0eaaa82d55004/lib/tasks/user.rake#L45

How many layers should we default to, @diegomeria?

**Comment by apercas** [comment]
Sure, get rid of the bug tag, I didn't know that.

**Comment by jjmata** [comment]
In conversation with @diegomeria this week he mentioned that 12 is the number he was thinking about.  Here is my question however: should we have 12 layers (or more) for the `premium` price point, and leave 8 for `basic`?

Implicitly _free_ gets 0 layers (since they don't have a builder account, but in actuality they get however many layers we decide are needed to compose they default visualization they get from us "for free" ... another way of upgrading them is if they want to add information (layers) they need to go up to _basic_ or _premium_, right?

What do you think, Diego?

**Comment by diegomeria** [comment]
@jjmata. Yes, I agree with that. A good criterion to ask customers the need to upgrade their license between Basic and Premium could be that: The moment they want to start uploading their own information on the farm (I suppose excluding drone flights and a basic index? ). There may be Basics that make flights and just want to see them on the platform.

All this as a criterion of upgrading outside the Agroguias.
