### ISSUE TITLE
Improve GPS accuracy (via py-photomassager?)

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#9]
Probably through the use of a better external GPS unit and/or RTK networks.

Feel free to edit this first comment to specify your goals for this milestone, @ivanprado.

**Comment by ivanprado** [comment]
**The problem**: Garmin GPS tracking generates a lot of noise (because of vibrations?). Corrections with Kalman filter flavoring reported speed seems to improve results... but we should explore other options for GPS.

**What I have discovered**: 
- Post processing using open GNSS could improve accuracy. Example of [CyL GNSS network](http://gnss.itacyl.es/). But you need a unit the save raw pseudoranges (typically on RINEX format). [RTKLIB](https://github.com/tomojitakasu/RTKLIB) seems to be the open source standard for post processing or even real-time RTK.
- There are two types of GNSS receivers: single frequency (L1) or double frequency (L1/L2). Single frequency are not as accurate as double frequency, but costs for L1/L2 are huge (more than $2K)

**Hardware minimum requirements**
- With battery
- Ready to use
- Saving raw data for post processing (RINEX)
- Enough precision between measures 

Others:
- Being able to [save waypoints ](https://community.emlid.com/t/reach-refresh-rate-for-camera-events/2866/3) when camera took a photo. 

**Found hardware**
- [Emid Reach RS](https://reachrs.emlid.com/). L1 RTK based on [u-blox chipset](http://www.insidegnss.com/node/5351) and RTKLIB. 
  - Pros:
    - Very complete: WiFi, LoRa, good battery, antena, robust, web interface, RTK. 
    - Price: $800. Not cheap but less than $1K
  - Cons: 
    - Single frequency.

It is not being easy to find relative cheap GNSS solutions ready to use with enough precision. Many chipsets at good price, but not already packed devices. 

**Comments from CyL GNSS people**


> Aparte tu pregunta tiene demasiadas variables para tener una respuesta clara. Lo que te puedo decir a grandes rasgos:
> - Si  vas a montar un autoguiado, necesitas un receptor que soporte recibir correcciones RTCM en tiempo real (lo que nosotros difundimos en la Red GNSS) y con una  frecuencia de receptor de al menos 10 HZ.
> - Si solo quieres posición en postproceso, necesitas un receptor (probablemente más barato) que al menos emita observaciones en formato RTCM, a 1 HZ para que algún software en tiempo real (ej: BKG NTRIP client BNC: https://igs.bkg.bund.de/ntrip/download) lo convierta en ficheros RINEX y luego los postproceses con otro software contra los RINEX de la Red GNSS.  Mejor si el receptor ya graba RINEX o algún formato propietario de observaciones (mdb, t01/t02), pues evitas tener un portátil en el vehículo para transformar en tiempo real RTCM>BNC>RINEX.
>
> -La precisión es un tema fundamental, tanto en tiempo real como en postproceso puedes conseguir precisión centimétrica con el receptor adecuado, pero tienes que definir que precisión submétrica quieres conseguir (70 cm, 50 cm, 10cm,?) y si quieres que esta precisión sea absoluta (en días distintos hay repetibilidad) o relativa entre pasadas (en un intervalo temporal de minutos no cambia posición, pero sí cambia mucho en horas o días) , pues esto afecta al precio del receptor.
> 
> -Básicamente  tienes que elegir entre montar un receptor de 1 frecuencia o de doble frecuencia (ambos con seguimiento de fase (carrier Phase)). Yo os recomiendo probar algún receptor de 1 frecuencia con seguimiento de fase, bastante más baratos que los de doble frecuencia, y si puede grabar observables en formato propietario o RINEX, pues mejor. Luego se trata de probar si al postprocesar os da la precisión absoluta /entre pasadas que buscáis, lo cual depende también de la distancia a la estación base más cercana, un equipo de fase de 1 frecuencia a partir de 10-20 km de la estación más cercana tendrá problemas para conseguir precisión centimétrica, un  equipo de doble frecuencia (más caro)  es capaz de corregir el 99% del error ionosférico por si mismo,  y tendrá precisión centimétrica a 50-60 km de la estación más cercana.


> [Talking about Emid Reach RS] Por lo que veo ese equipo es de una frecuencia. Usa una placa u-blox y hace RTK en L1 con las librerías RTKLIB. Es una solución RTK frágil, que puede necesitar tiempo en fijar ambigüedades y requiere de una distancia a la base cercana. Aun así el precio es excepcional y puede ser una solución muy interesante.
> http://www.insidegnss.com/node/5351
> Tenemos muchos usuarios de la red que usan un montaje similar para equipos de guiado en tractores.
 >
> Quizás puedes buscar otro receptor L1 e instalar RTKLIB en un dispositivo propio para hacer RTK y quizás te pueda salir aún más barato.

**TODO**
- Look for other possible hardware.

**Comment by ivanprado** [comment]
Interesting [this discussion](https://support.pix4d.com/hc/en-us/community/posts/204132893-Discussion-on-RTK-GPS-Systems-#gsc.tab=0) at pix4d blog

**Comment by ivanprado** [comment]
Closing this ticket by now as it is not a priority by now... Will reopen in future when needed.

**Comment by jjmata** [comment]
Makes sense, investigation gave us a few leads and if need to purchase new hardware we may do so for the VINTEGRA project.
